services:
  client:
    build:
      context: .
      target: development
    image: devops-exams-react
    container_name: devops-exams-client
    restart: unless-stopped
    env_file: .env
    ports:
      - "5173:5173"
    networks:
      - devops-exams-net
    depends_on:
      - server
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./public
          target: /app/public
        - action: rebuild
          path: package.json
        - action: rebuild
          path: package-lock.json

