services:
  server:
    build:
      context: .
      target: development
    container_name: mern-server
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - mern-network
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json
        - action: rebuild
          path: package-lock.json

networks:
  mern-network:
    driver: bridge
