services:
  server:
    build:
      context: .
      target: development
    image: devops-exams-express
    container_name: devops-exams-server
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - devops-exams-net
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json
        - action: rebuild
          path: package-lock.json

networks:
  devops-exams-net:
    driver: bridge
